# Generated by Django 5.1.5 on 2025-01-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_is_student_profile_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
