# Generated by Django 5.1.5 on 2025-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_files_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='urll',
            field=models.URLField(blank=True, null=True),
        ),
    ]
