# Generated by Django 5.1.5 on 2025-02-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_urll_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
    ]
